### ISSUE TITLE
Question about calculating dense mentions

### ISSUE THREAD

**Issue by ianporada** [ufal/crac2023-corpipe#2]
Hi, very nice model!

I am trying to understand the parsing of CorefUD mentions using udapi. Specifically I have a question about these lines:

```python
while start > 0 and span[start - 1].ord + 1 == span[start].ord: start -= 1
while end < len(span) - 1 and span[end].ord + 1== span[end + 1].ord: end += 1
dense_mentions.append(((span[start].ord - 1, span[end].ord - 1), mention.entity.eid, start > 0 or end + 1 < len(span)))
```

which are located here: https://github.com/ufal/crac2023-corpipe/blob/43cfb7c86181017afeac8953ebfcf73078fc6d94/corpipe23.py#L127C28-L127C48

I am wondering why the mention span `(span[start].ord - 1, span[end].ord - 1)` isn't simply calculated as `(span[0].ord - 1, span[-1].ord - 1)`. Is this to avoid including zeros in the span? As far as I know the condition in the loop `span[start - 1].ord + 1 == span[start].ord` will only be false if at least one of the tokens is a zero and thus has a non-integer ord.

(If I am right udapi will not include multi-word tokens in the span which is another thought I had for why mentions might be calculated this way.)

Thanks so much!

**Comment by ianporada** [comment]
Oh I think I understand. This is a way of reformatting discontinuous spans as the largest continuous subspan that contains the head token?

**Comment by foxik** [comment]
Yes, exactly. We could in theory predict discontinuous spans as discontinuous, but it would require additional operations in our tag set (apart form PUSH and POP we would require something like APPEND), and we did not go that way. We could also use a smallest continuous span containing all tokens of a discontinuous span, but in the CRAC22 edition predicting a token out of golden span was penalized, which is why we use a largest continuous subspan containing the head.
